In [5]:
import sys 
from pathlib import Path
import os

In [9]:
parent_dir = Path(os.getcwd()).resolve().parent
parent_dir

PosixPath('/home/jin/gpt2_from_scratch')

In [11]:
sys.path.insert(0, str(parent_dir))

In [15]:
from gpt2.config import GPT2Config
from multihead_attn import MultiHeadAttention

In [14]:
config = GPT2Config()

config.context_length

1024

In [17]:
mhattn = MultiHeadAttention(d_in=config.emb_dim, d_out=config.emb_dim, context_length=config.context_length, dropout=config.drop_rate, num_heads=config.n_heads)

In [18]:
mhattn

MultiHeadAttention(
  (W_query): Linear(in_features=768, out_features=768, bias=False)
  (W_key): Linear(in_features=768, out_features=768, bias=False)
  (W_value): Linear(in_features=768, out_features=768, bias=False)
  (out_proj): Linear(in_features=768, out_features=768, bias=True)
  (dropout): Dropout(p=0.1, inplace=False)
)

In [19]:
import torch 
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [24]:
batch = torch.stack((inputs, inputs), dim=0)

In [25]:
batch.shape

torch.Size([2, 6, 3])

In [26]:
batch

tensor([[[0.4300, 0.1500, 0.8900],
         [0.5500, 0.8700, 0.6600],
         [0.5700, 0.8500, 0.6400],
         [0.2200, 0.5800, 0.3300],
         [0.7700, 0.2500, 0.1000],
         [0.0500, 0.8000, 0.5500]],

        [[0.4300, 0.1500, 0.8900],
         [0.5500, 0.8700, 0.6600],
         [0.5700, 0.8500, 0.6400],
         [0.2200, 0.5800, 0.3300],
         [0.7700, 0.2500, 0.1000],
         [0.0500, 0.8000, 0.5500]]])

In [31]:
mhattn2 = MultiHeadAttention(d_in=3, d_out=2, context_length=20, dropout=0.1, num_heads=2)

In [33]:
context_vec = mhattn2(batch)
context_vec

tensor([[[ 0.7295, -0.1665],
         [ 0.7407, -0.1827],
         [ 0.7428, -0.1680],
         [ 0.7582, -0.1702],
         [ 0.7507, -0.1693],
         [ 0.7148, -0.1878]],

        [[ 0.7237, -0.1886],
         [ 0.7588, -0.1698],
         [ 0.7588, -0.1698],
         [ 0.6875, -0.2204],
         [ 0.7573, -0.1709],
         [ 0.7583, -0.1701]]], grad_fn=<ViewBackward0>)

In [34]:
context_vec.shape

torch.Size([2, 6, 2])

In [38]:
mhattn3 = MultiHeadAttention(d_in=3, d_out=6, context_length=20, dropout=0.1, num_heads=3)

In [40]:
context_vec3 = mhattn3(batch)
context_vec3, context_vec3.shape

(tensor([[[ 0.4865,  0.4277, -0.3363, -0.3032, -0.1415, -0.3766],
          [ 0.4774,  0.4242, -0.3398, -0.3049, -0.1403, -0.3755],
          [ 0.4672,  0.4218, -0.3516, -0.2845, -0.1429, -0.3842],
          [ 0.4104,  0.3856, -0.3526, -0.2822, -0.1214, -0.3363],
          [ 0.4829,  0.4285, -0.3373, -0.3016, -0.1437, -0.3777],
          [ 0.4737,  0.4240, -0.3395, -0.3047, -0.1415, -0.3741]],
 
         [[ 0.4865,  0.4277, -0.3363, -0.3032, -0.1415, -0.3766],
          [ 0.5035,  0.4312, -0.3267, -0.2956, -0.1273, -0.3662],
          [ 0.4834,  0.4270, -0.3383, -0.3018, -0.1423, -0.3775],
          [ 0.4796,  0.4272, -0.3378, -0.3017, -0.1438, -0.3762],
          [ 0.4845,  0.4115, -0.3396, -0.2743, -0.1114, -0.3593],
          [ 0.5000,  0.4309, -0.3262, -0.2954, -0.1280, -0.3643]]],
        grad_fn=<ViewBackward0>),
 torch.Size([2, 6, 6]))